# Compile configuration
DMD ?= dmd
DEBUGFLAGS ?= -g -debug
RELEASEFLAGS ?= -O -release -noboundscheck

OUTPUTDIR ?= lib
LIBEXT ?= a

LINKERFLAGS ?= -L-ldl -L-lev $(LDFLAGS)

COMMONFLAGS = -lib -Ilibev -w -wi -de $(LINKERFLAGS) $(DFLAGS)

# Targets
DEBUG_NAME = $(OUTPUTDIR)/dirk-d.$(LIBEXT)
RELEASE_NAME = $(OUTPUTDIR)/dirk.$(LIBEXT)

.PHONY: debug release clean

all: debug release

debug: $(DEBUG_NAME)
release: $(RELEASE_NAME)

$(DEBUG_NAME): $(SOURCES)
	$(DMD) $(DEBUGFLAGS) $(COMMONFLAGS) -of$(DEBUG_NAME) $(SOURCES)

$(RELEASE_NAME): $(SOURCES)
	$(DMD) $(RELEASEFLAGS) $(COMMONFLAGS) -of$(RELEASE_NAME) $(SOURCES)

clean:
	rm $(DEBUG_NAME)
	rm $(RELEASE_NAME)

# Automatically generated by list_sources.d
IRC_SOURCES = \
	irc/client.d \
	irc/ctcp.d \
	irc/dcc.d \
	irc/eventloop.d \
	irc/exception.d \
	irc/linebuffer.d \
	irc/protocol.d \
	irc/testing.d \
	irc/tracker.d \
	irc/url.d \
	irc/util.d

LIBEV_SOURCES = \
	libev/deimos/ev.d

LOADER_SOURCES = \
	loader/loader.d \
	loader/posix.d \
	loader/windows.d

SSL_SOURCES = \
	ssl/openssl.d \
	ssl/socket.d

SOURCES = $(IRC_SOURCES) $(LIBEV_SOURCES) $(LOADER_SOURCES) $(SSL_SOURCES)  
